### ISSUE TITLE
Error compiling TGRSIMnemonic

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/GRSIData#66]
There is a compilation issue in the current main branch for the `TGRSIMnemonic.h` header file. 

```
Compiling .build/libraries/TGRSIAnalysis/TS3/TS3Hit.o[ERROR]
In file included from libraries/TGRSIAnalysis/TS3/TS3Hit.cxx:7:
/home/S9038/GRSISort/v4.0.0.2/GRSIData/include/TGRSIMnemonic.h:63:9: error: ‘double TGRSIMnemonic::GetTime(Long64_t, Float_t, double, const TChannel*) const’ marked ‘override’, but does not override
   63 |  double GetTime(Long64_t timestamp, Float_t cfd, double energy, const TChannel* channel) const override;
      |         ^~~~~~~
make: *** [makefile:170: .build/libraries/TGRSIAnalysis/TS3/TS3Hit.o] Error 1
```

I remove the `override` from the end of the line and it compiled. 

As always this may be a machine dependent issue.

**Comment by cnatzke** [comment]
Here's another error:
```
Compiling .build/libraries/TGRSIFormat/TGRSIMnemonic.o[ERROR]
In file included from libraries/TGRSIFormat/TGRSIMnemonic.cxx:1:
/home/S9038/GRSISort/v4.0.0.2/GRSIData/include/TGRSIMnemonic.h:63:71: error: ‘TChannel’ does not name a type
   63 |  double GetTime(Long64_t timestamp, Float_t cfd, double energy, const TChannel* channel) const;
      |                                                                       ^~~~~~~~
libraries/TGRSIFormat/TGRSIMnemonic.cxx: In member function ‘virtual void TGRSIMnemonic::Parse(std::string*)’:
libraries/TGRSIFormat/TGRSIMnemonic.cxx:138:10: error: ‘SetRFMnemonic’ was not declared in this scope
  138 |          SetRFMnemonic(name);
      |          ^~~~~~~~~~~~~
libraries/TGRSIFormat/TGRSIMnemonic.cxx: At global scope:
libraries/TGRSIFormat/TGRSIMnemonic.cxx:203:8: error: no declaration matches ‘double TGRSIMnemonic::GetTime(Long64_t, Float_t, double, const TChannel*) const’
  203 | double TGRSIMnemonic::GetTime(Long64_t timestamp, Float_t cfd, double energy, const TChannel* channel) const
      |        ^~~~~~~~~~~~~
In file included from libraries/TGRSIFormat/TGRSIMnemonic.cxx:1:
/home/S9038/GRSISort/v4.0.0.2/GRSIData/include/TGRSIMnemonic.h:63:9: note: candidate is: ‘double TGRSIMnemonic::GetTime(Long64_t, Float_t, double, const int*) const’
   63 |  double GetTime(Long64_t timestamp, Float_t cfd, double energy, const TChannel* channel) const;
      |         ^~~~~~~
In file included from libraries/TGRSIFormat/TGRSIMnemonic.cxx:1:
/home/S9038/GRSISort/v4.0.0.2/GRSIData/include/TGRSIMnemonic.h:11:7: note: ‘class TGRSIMnemonic’ defined here
   11 | class TGRSIMnemonic : public TMnemonic {
      |       ^~~~~~~~~~~~~
make: *** [makefile:170: .build/libraries/TGRSIFormat/TGRSIMnemonic.o] Error 1
```

I am using the most up to date versions of GRSIData and GRSISort and trying to compile on a  Ubuntu 20.04 machine.

**Comment by VinzenzBildstein** [comment]
What exact commit are you on (result from ```git log -n 1```)? I'm using 
```
commit 0bb96b2c793c4aa55759a8ebfb4971f16e6b1d4f (HEAD -> master, upstream/master)
Merge: 23091bd6 505cdd2c
Author: Vinzenz Bildstein <vbildste@uoguelph.ca>
Date:   Mon Mar 7 15:32:16 2022 -0500

    Merge pull request #1242 from VinzenzBildstein/master
    
    Fixed bug in TSinglePeak::Print
```
for GRSISort and 
```
commit 933616120f34da0d6bd4b5c3153e51372fb6dabb (HEAD -> master, upstream/master)
Merge: 6f379d9 29231a0
Author: Vinzenz Bildstein <vbildste@uoguelph.ca>
Date:   Fri Mar 4 16:16:10 2022 -0500

    Merge pull request #65 from VinzenzBildstein/master
    
    Moved TGRSIDetectorHit::GetTime to TGRSIMnemonic::GetTime and removed TGRSIDetectorHit
```
for GRSIData and it compiles fine using Ubuntu 20.04.4

**Comment by cnatzke** [comment]
GRSIData:
```
commit 933616120f34da0d6bd4b5c3153e51372fb6dabb (HEAD -> master, origin/master, origin/HEAD)
Merge: 6f379d9 29231a0
Author: Vinzenz Bildstein <vbildste@uoguelph.ca>
Date:   Fri Mar 4 16:16:10 2022 -0500

    Merge pull request #65 from VinzenzBildstein/master

    Moved TGRSIDetectorHit::GetTime to TGRSIMnemonic::GetTime and removed TGRSIDetectorHit
```

GRSISort:
```
commit 9b6e40d1f3335049805a2766c2913e93c95833a5 (HEAD -> master, origin/master, origin/HEAD)
Merge: 9dbf0a3f 911396ce
Author: Vinzenz Bildstein <vbildste@uoguelph.ca>
Date:   Wed Jun 23 20:58:51 2021 -0400

    Merge pull request #1185 from VinzenzBildstein/master

    Added bin directories of data parser libraries to PATH
```

**Comment by cnatzke** [comment]
Updating my GRSISort to the latest commit fixed the issue. Thanks!

**Comment by cnatzke** [comment]
Maybe I spoke too soon, the compilation failed at a new point:
```
Compiling /home/S9038/GRSISort/v4.0.0.2/bin/tac_calibrator[ERROR]
/usr/bin/ld: /home/S9038/GRSISort/v4.0.0.2/GRSIData/lib/libTMidas.so: undefined reference to `TChannel::SetDigitizerType(TPriorityValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'
collect2: error: ld returned 1 exit status
make: *** [makefile:151: /home/S9038/GRSISort/v4.0.0.2/bin/tac_calibrator] Error 1
```

**Comment by VinzenzBildstein** [comment]
Oh, try the latest version, I pushed a change for one line in TChannel.cxx today that was screwing things up (though it did compile fine for me which I don't understand).

**Comment by cnatzke** [comment]
I don't think the change got pushed. I can't pull anything newer than the commit I used above.

**Comment by VinzenzBildstein** [comment]
Sorry, this is not an issue of GRSIData, but of GRSISort, so you need to pull GRIFFINCollaboration/GRSISort#1243

**Comment by cnatzke** [comment]
Ah, I pulled that commit and everything compiled. 

I do get this warning when running grsisort: 
```
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGRSIDetectorHit.h
   requested to autoload type TGRSIDetectorHit
	grsisort version 4.0.0.3
	Using library /home/S9038/GRSISort/v4.0.0.2/GRSIData/lib/libGRSIData.so version 0.1.1.2
```

**Comment by VinzenzBildstein** [comment]
Okay, so is this solved for you, aka can we close this issue?

**Comment by cnatzke** [comment]
Yes, I just wanted to make sure you didn't have anything else to add.
